name: KAP Bot Notification

on:
  schedule:
    # Her 10 dakikada bir çalışacak
    - cron: "*/10 * * * *"
  workflow_dispatch: # manuel tetikleme için

jobs:
  run-kap-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install requests tabulate

    - name: Run KAP bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python test.py
